apiVersion: v1
kind: Service
metadata:
  name: cpp-kubernetes-app-service
spec:
  type: LoadBalancer
  selector:
    app: cpp-kubernetes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
