name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build C++ Application
      run: |
        mkdir -p build
        cd build
        cmake ../src
        make

    - name: Build Docker Image
      run: |
        cd build
        docker build -t cpp-kubernetes-app:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: docker push cpp-kubernetes-app:latest

    - name: Configure kubectl
      run: aws eks --region us-west-2 update-kubeconfig --name cpp-kubernetes-app-cluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/cpp-kubernetes-app-deployment.yaml
        kubectl apply -f k8s/cpp-kubernetes-app-service.yaml
